spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Gyw020409
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # 配置xml映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置日志实现
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段名
      logic-not-delete-value: 0 # 逻辑删除未删除的值
      logic-delete-value: 1 # 已删除的值

server:
  port: 8000

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tSqodN3zQnyWFD1VE8b
  accessKeySecret: sqCd3ye50H2H9W7xrLtXfsceEoBdPD
  bucketName: gbd-forum
